# -*- coding: utf-8 -*-
"""find duplicate elements   Leetcode 217.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EBy7aZDdiOKNY8IxCSFhxVt_UB79WQIo
"""

#find duplicate elements   Leetcode 217

def dup(lists):  #find duplicate elements  #217
  hashtable={}
  for idx, element in enumerate(lists):
    if element not in hashtable:
      hashtable[element]=idx
    else:
      return 'True'
  return 'false'

dup([1,2,3,4,2])

