# -*- coding: utf-8 -*-
"""Hash table code basics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vtckvjQtBikGqE9kAVHRIMNFGohwKy29
"""

class hashtable:
  def __init__(self):
    self.max=100
    self.array=[None for i in range(self.max)]

  def hashfunction(self, key):
    h=0
    for i in key:
      h+=ord(i)
    return h % self.max

  def __getitem__(self, key):
    h=self.hashfunction(key)
    return self.array[h]

  def __setitem__(self, key, value):
    h=self.hashfunction(key)
    self.array[h]=value
  

  def __delitem__(self,key):
    h=self.hashfunction(key)
    self.array[h]=None

t=hashtable()
t['hi']=10

t['hi']

t.array

