# -*- coding: utf-8 -*-
"""Sliding window Leetcode 121.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EBy7aZDdiOKNY8IxCSFhxVt_UB79WQIo
"""

# Sliding window Leetcode 121

def maxprof(lists):  # sliding window #121
  left, right=0, 1
  maxprofit=0
  while right<len(lists):
    if lists[left]<lists[right]:
      profit=lists[right]-lists[left]
      maxprofit=max(maxprofit, profit)
    else:
      left=right
    right+=1
  return maxprofit

maxprof([7,1,5,3,6,0,9])

