# -*- coding: utf-8 -*-
"""Two sum problem Leetcode 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EBy7aZDdiOKNY8IxCSFhxVt_UB79WQIo
"""

# Two sum problem Leetcode 1

def twosum(lists, total): #1
  hashmap={}
  for idx, key in enumerate(lists):
    remaining=total-key
    if remaining not in hashmap:
      hashmap[key]=idx
    else:
      return (idx, hashmap[remaining])

twosum([1,2,3,4], 7)